const eetd_data = {
    1 : {
        'name' : 'Pequeña Mancha te enseña cómo transformarte',
        'type' : 'Laboratorio creativo',
        'author' : 'Antonio Toledo',
        'description' : 'Recomendado para niñas y niños a partir de 1 año de edad acompañados de un adulto.',
        'url' : 'https://www.youtube.com/embed/fSIXD5rXMYQ',
    },
    2 : {
        'name' : 'Me juego.',
        'type' : 'Laboratorio creativo',
        'author' : 'Flor Sandoval',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad acompañados de un adulto.',
        'url' : 'https://www.youtube.com/embed/OzB0DXGHwWg',
    },
    3 : {
        'name' : 'Juanito, el niño que no le tenía miedo a nada',
        'type' : 'Narración oral',
        'author' : 'Benjamín Briseño',
        'description' : 'Recomendado para niñas y niños a partir de 10 años de edad.',
        'url' : 'https://www.youtube.com/embed/un-AyuCjtEE',
    },
    4 : {
        'name' : 'La vaca cuenta',
        'type' : 'Teatro de Títeres',
        'author' : 'Marionetas de la esquina',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad.',
        'url' : 'https://www.youtube.com/embed/5NYUlEFvWnc',
    },
    5 : {
        'name' : 'Lanzando y jugando',
        'type' : 'Laboratorio creativo',
        'author' : 'Natalia Cárdenas',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/IQWhc1vUbJ4',
    },
    6 : {
        'name' : 'Por qué la ballena tiene tan singular garganta',
        'type' : 'Narración oral',
        'author' : 'Nacho Casas',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/zusZGa_WNss',
    },
    7 : {
        'name' : 'Baila',
        'type' : 'Música',
        'author' : 'Monedita de Oro',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Baila las canciones "Las mamás tienen radar" y "Mamá Fesibuquera".',
        'url' : 'https://www.youtube.com/embed/KbfLPiiypD4',
    },
    8 : {
        'name' : 'Un viaje dentro del corazón',
        'type' : 'Laboratorio creativo',
        'author' : 'Oliver Miranda',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Leamos juntos el libro Koben, de la mano de Oliver Miranda y Nancy Mendoza.',
        'url' : 'https://www.youtube.com/embed/znX0VbDLUuo',
    },
    9 : {
        'name' : 'Concierto de música changosa',
        'type' : 'Música',
        'author' : 'Radio Gorila',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/MFbfsU7Wpd8',
    },
    10 : {
        'name' : 'Marina. Imaginación',
        'type' : 'Narración oral y música',
        'author' : 'Norma Torres',
        'description' : 'Recomendado para niñas y niños a partir de 7 años de edad. Narración inspirada en "Sueño Desvelado", de Rafael Pérez Estrada.',
        'url' : 'https://www.youtube.com/embed/lrJfjAaxWyE',
    },
    11 : {
        'name' : 'Música para jugar en casa',
        'type' : 'Música',
        'author' : 'Mariana Mallol',
        'description' : 'Recomendado para niñas y niños a partir de 2 años de edad.',
        'url' : 'https://www.youtube.com/embed/byfATTC3SA0',
    }, 
};