const retos_data = {
    1 : {
        'name' : 'Te reto a... decir un trabalenguas con ritmo',
        'type' : 'Música',
        'author' : 'Kevin Galeana, narrador',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/zju_qD7YA70', 
    },
    2 : {
        'name' : 'Te reto a... poner color a los sonidos',
        'type' : 'Música y pintura',
        'author' : 'Norma Guerrero, tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/IDg_zx--r2E', 
    },
    3 : {
        'name' : 'Te reto a... hacer el reportaje de la noche',
        'type' : 'Narrativa',
        'author' : 'Libia Ennedi, tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/98Ojp1l91no', 
    },
    4 : {
        'name' : 'Te reto a... hacer un dibujo con sombras',
        'type' : 'Artes plásticas',
        'author' : 'Claudia Vences, artista plástica',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/fxAzn5SxWVc',
    },
    5 : {
        'name' : 'Te reto a... bailar el Ailingo lilingo',
        'type' : 'Laboratorio creativo',
        'author' : 'Liliana Gama',
        'description' : '¿Sabes cuántas danzas y bailes hay en nuestro país? La chilena es una música afromexicana de Oaxaca y Guerrero. Te retamos a zapatear con este ritmo, sólo necesitas un pañuelo o la servilleta de las tortillas.',
        'url' : 'https://www.youtube.com/embed/E5TYDdn0w6A',
    },
    6 : {
        'name' : 'Te reto a... hacer máscaras para explorar',
        'type' : 'Artes plásticas',
        'author' : 'Isabel Aguerrebere, tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/QM8sQecMT_g',
    },
    7 : {
        'name' : 'Te reto a... hacer poemas repentistas',
        'type' : 'Poesía',
        'author' : 'Karloz Atl, tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/Oq4kBM55zgk',
    },
    8 : {
        'name' : 'Te reto a... usar palabras en mazateco de Oaxaca',
        'type' : 'Oralidad',
        'author' : 'Filogonio, artista plástico',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/y_MwWSpKupk',
    },
    9 : {
        'name' : 'Te reto a... probar tus pulmones',
        'type' : 'Oralidad',
        'author' : 'Xolocotzin, artista sonoro',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/fLB9KpFv1N4',
    },
    10 : {
        'name' : 'Te reto a... contar tus extrañamientos',
        'type' : 'Artes plásticas',
        'author' : 'Claudia Vences, artista visual',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/KghgrmEKDDw',
    },
    11 : {
        'name' : 'Te reto a... grabar música con ruiditos',
        'type' : 'Laboratorio creativo',
        'author' : 'Germán Hinojosa, tallerista',
        'description' : '¿Te has preguntado qué tipo de música genera el agua en una olla? La melodía que resulta es electroacústica, sí, así como lees. Hagamos una composición a partir de los ruidos de objetos cotidianos. ¿Qué dices?',
        'url' : 'https://www.youtube.com/embed/-knl7ygyt7k',
    }, 
    12 : {
        'name' : 'Te reto a... ser un gran explorador',
        'type' : 'Laboratorio creativo: fotografía',
        'author' : 'Sara Watson, Jóvenes Construyendo el Futuro en Alas y Raíces',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/7Nn3VJZOplk',
    },  
    13 : {
        'name' : 'Te reto a... seguir unos pasos de baile con sonido (Danza)',
        'type' : 'Laboratorio creativo',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto, talleristas',
        'description' : '¡Hagamos una canción que acumule movimientos y sonidos! Mediante juegos y pasos divertidos, construiremos una secuencia changosa para construir una frase de música y danza. ¿Te animas?',
        'url' : 'https://www.youtube.com/embed/2crDxztAz1E',
    },
    14 : {
        'name' : 'Te reto a... dibujar la respuesta a esta adivinanza',
        'type' : 'Oralidad',
        'author' : 'Kevin Galeana, narrador',
        'description' : 'Alas y Raíces te reta a escuchar, pensar, adivinar y dibujar la respuesta a esta adivinanza.',
        'url' : 'https://www.youtube.com/embed/D67LKZEmZ0Y',
    },
    15 : {
        'name' : 'Te reto a... hacer tu autorretrato literario',
        'type' : 'Narraciones orales',
        'author' : 'Raúl Pérez Buendía, narrador',
        'description' : 'Tras la lectura de Autorretrato, de Miguel de Cervantes Saavedra... Te reto a que escribas tu propio autorretrato literario y lo acompañes con tu mejor fotografía.',
        'url' : 'https://www.youtube.com/embed/6paSxYjxxVU',
    },
    16 : {
        'name' : 'Te reto a... hacer un bocón',
        'type' : 'Laboratorio creativo',
        'author' : 'Claudia Vences, tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Un bocón es un dibujo expandido que guarda un secreto. Y tú, ¿a quién retas?',
        'url' : 'https://www.youtube.com/embed/HpSKuzR7Xy8',
    },
    17 : {
        'name' : 'Te reto a... darte tu taco (Gastronomía)',
        'type' : 'Presentación artística',
        'author' : 'Martín Corona, tallerista',
        'description' : 'Hacer el taco más raro, más extraño, más sabroso y comérselo. No se vale desperdiciar comida y hay que hacerlo con lo que tengas en casa. ¿Puedes hacer un taco postre? O ¿podrás comer un taco con extra limón?',
        'url' : 'https://www.youtube.com/embed/j_3EV_Y7nvU',
    },
    18 : {
        'name' : 'Te reto a... armar tu batería',
        'type' : 'Laboratorio creativo: Música',
        'author' : 'David Alva, tallerista',
        'description' : '¿Sabes que en casa tienes artefactos que pueden servir de instrumentos de percusión? ¿Te has preguntado cómo suena la cubeta vieja de casa, las ollas o las cucharas? Crea tus propios ritmos, mezclando sonidos de cosas que te rodeen y haz grandes piezas musicales.',
        'url' : 'https://www.youtube.com/embed/aG_TInLlVbU',
    }, 
    19 : {
        'name' : 'Te reto a... contar mariposas',
        'type' : 'Juego',
        'author' : 'Astrid Perellón, narradora',
        'description' : '¿Cuántas mariposas puedes ver en un día sin salir de casa? Astrid Perellón te dice cómo le puedes hacer para enseñar a tus ojos a ver ¡lo que tú quieras!, y te invita a realizar este reto y a compartirnos cuántas mariposas viste en un solo día.',
        'url' : 'https://www.youtube.com/embed/_0Yv-EYOn_c',
    },
    20 : {
        'name' : 'Te reto a... animar juntos desde casa',
        'type' : 'Laboratorio creativo: Animación',
        'author' : 'Iván Pacifuentes, tallerista',
        'description' : 'Si eres observador, te darás cuenta que tu juguete, lápiz o una simple cajita de cartón, puede cobrar vida a través del movimiento. Hoy, te retamos a crear una toma en movimiento, en stop motion. Para ello necesitas un celular, plastilina, un juguete u objetos que tengas en casa y una app que descargarás en un celular para unir las imágenes y crear el video o gif ; ¡ah! y también necesitarás mucha imaginación.',
        'url' : 'https://www.youtube.com/embed/H3yiHnElXWI',
    }, 
    21 : {
        'name' : 'Te reto a... buscar guardianes en casa',
        'type' : 'Laboratorio creativo: Fotografía',
        'author' : 'Martín Corona, tallerista',
        'description' : '¿Te has dado cuenta que a tu alrededor hay muchas cosas que parecen otra cosa? Te retamos a buscar los guardianes que hay en casa y los personajes escondidos, con una cámara o celular busca caras, formas que asemejen una criatura, rostros escondidos en los muebles o paredes de casa, para fotografiarlos y armarles una historia ¿Qué monstruos, duendes o extraños individuos habitan tu hogar?',
        'url' : 'https://www.youtube.com/embed/h8ZF7-oNNwc',
    }, 
    22 : {
        'name' : 'Te reto a... imaginar historias',
        'type' : 'Presentación artística',
        'author' : 'Compañía La Trouppe',
        'description' : 'Seguro que en tu casa hay un cuadro colgado o una fotografía, ¿Si? ¡Qué bien! Te invitamos a crear historias fantásticas; sólo necesitas abrir bien los ojos e imaginar, Lady Lucas te dirá como hacerlo.',
        'url' : 'https://www.youtube.com/embed/66UnTC7IG54',
    },
    23 : {
        'name' : 'Te reto a... soplar una bolsa de plástico',
        'type' : 'Expresión corporal',
        'author' : 'Natalia Cárdenas, tallerista',
        'description' : 'Hagamos una danza con el viento y una bolsa, ¿te animas?',
        'url' : 'https://www.youtube.com/embed/_ozfpD27bUs',
    },
    24 : {
        'name' : 'Te reto a... hacer una coreografía con tus manos, a ritmo de swing',
        'type' : 'Taller de danza',
        'author' : 'Norma Torres, narradora',
        'description' : 'Alas y Raíces te reta a bailar con las manos.',
        'url' : 'https://www.youtube.com/embed/fdHXvRmVDrc',
    }, 
    25 : {
        'name' : 'Te reto a... hacer el librito de los extrañamientos',
        'type' : 'Presentación artística',
        'author' : 'Claudia Vences, artista plástica',
        'description' : 'Dibuja, escribe, recorta o pega lo que más extrañas y compártelo con nosotros.',
        'url' : 'https://www.youtube.com/embed/LmlftNTeTiw',
    },
    26 : {
        'name' : 'Te reto a... hacer música con tu cuerpo y voz',
        'type' : 'Presentación artística',
        'author' : 'Daniel Sánchez, tallerista',
        'description' : 'Todo en la vida tiene sonido, se mueve, vibra, está vivo. Nuestro mundo suena, nuestro cuerpo también, hoy te invitamos a descubri qué sonidos puedes hacer con tu voz y cuerpo.',
        'url' : 'https://www.youtube.com/embed/Q_9-YCtyeoI',
    }, 
    27 : {
        'name' : 'Te reto a... cambiar el final de Caperucita Roja',
        'type' : 'Presentación artística',
        'author' : 'Ángel Aranda, narrador',
        'description' : 'Alas y Raíces te reta a proponer un final alternativo al cuento de Caperucita Roja.',
        'url' : 'https://www.youtube.com/embed/0-V9RMYM_h4',
    },
    28 : {
        'name' : 'Te reto a... hacer un castillo medieval',
        'type' : 'Presentación artística',
        'author' : 'Compañía La Trouppe',
        'description' : 'Construye un castillo medieval con materiales que tienes en casa, recuerda que tú eres el arquitecto y Lady Lucas solo te mostrará una forma, así que puedes construirlo de formas nunca antes vistas.',
        'url' : 'https://www.youtube.com/embed/lJ8FIF5glSU',
    },
    29 : {
        'name' : 'Te reto a... crear tu propio instrumento musical',
        'type' : 'Laboratorio creativo',
        'author' : 'Norma Torres, narradora',
        'description' : 'Crea tu propio instrumento musical reciclando y recolectando objetos que encuentres en tu casa. ¡Dime con qué nos sorprenderás!',
        'url' : 'https://www.youtube.com/embed/atbaq730uAU',
    },
    30 : {
        'name' : 'Te reto a... hacer peinados chistosos. Colima',
        'type' : 'Expresión corporal',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto, talleristas',
        'description' : 'En estos días quizá nos cueste un poco peinarnos, quizá nuestro cabello quiere estar suelto y bailar al ritmo de los días, pero hoy te queremos retar a inventar nuevos y alocados peinados, al ritmo de tu música preferida, ¿te animas?',
        'url' : 'https://www.youtube.com/embed/pxddUXeptyE',
    },  
    31 : {
        'name' : 'Te reto a... mirar sin reír',
        'type' : 'Expresión corporal',
        'author' : 'Beto Batuca y los Baturetos',
        'description' : 'La música y el canto son un apoyo en el desarrollo del lenguaje, el ritmo y la conciencia corporalVitamina Sé es un proyecto de Alas y Raíces que ofrece contenidos para estimular las habilidades y la creatividad en niñas, niños y adolescentes a través de pequeñas cápsulas de cuentos, talleres, música y teatro durante la Jornada Nacional de Sana Distancia.',
        'url' : 'https://www.youtube.com/embed/PdYAylFhSys',
    }, 
    32 : {
        'name' : 'Te reto a... hacer un taumátropo',
        'type' : 'Laboratorio creativo',
        'author' : 'Iván Pacifuentes, tallerista',
        'description' : 'El día de hoy te retamos a hacer un taumátropo, ¿sabes qué es? es un juguete óptico que usa principios de la animación; así que te invitamos a aventurarte a animar tus dibujos favoritos y crear una pequeña secuencia de imágenes que al moverse ¡parecen cobrar vida!',
        'url' : 'https://www.youtube.com/embed/',
    },
    33 : {
        'name' : ' Te reto a... inventar leyendas divertidas',
        'type' : 'Música y narración oral',
        'author' : 'Cecilia y Diego, integrantes de Saltapatrás',
        'description' : '¿Imaginas las películas sin sonidos como la lluvia, o ese ring que nos espanta en una película de suspenso? ¡No! La musicalización es muy importante y queremos mostrarte algunos efectos básicos de sonido que puedes poner en las leyendas o cuentos que conozcas, ¿y por qué no? ¡que tú inventes!',
        'url' : 'https://www.youtube.com/embed/qnAoKefELt0',
    },
    34 : {
        'name' : 'Te reto a... hacer un Knee Spin',
        'type' : 'Breaking',
        'author' : 'Aramis, tallerista integrante de Spin Masters',
        'description' : '¿Sabes qué es el Breaking?, ¿cuáles son sus principales pasos?, Hoy te invitamos a conocer y hacer un Knee Spin, un paso básico del Breaking, recuerda que en el baile urbano, el estilo que tú le des a los pasos es lo más importante, así que ¡vamos a practicar! Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/_xTX6vk5l4A',
    },
    35 : {
        'name' : 'Te reto a... llenar el huacal de adivinanzas',
        'type' : 'Oralidad',
        'author' : 'Kevin Galeana, narrador',
        'description' : 'Alas y Raíces te reta a convertir este huacal en la colección de adivinanzas más grande del mundo.Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/nIGOJwaj5iM',
    }, 
    36 : {
        'name' : 'Te reto a... hacer un experimento con monedas',
        'type' : 'Ciencia',
        'author' : 'Julieta Montelongo, tallerista',
        'description' : '¿Sabías que la ciencia está en todos lados? Hoy te invitamos a realizar un pequeño pero muy divertido experimento sobre la densidad. Te sorprenderás de lo que descubrirás, ¿aceptas el reto? Recomendado para niñas y niños a partir de 9 años de edad.',
        'url' : 'https://www.youtube.com/embed/JX29w7KypDU',
    }, 
    37 : {
        'name' : 'Te reto a... dibujar a tu héroe',
        'type' : 'Pintura',
        'author' : 'Filogonio Naxin (Tallerista)',
        'description' : 'Los médicos de todo México nos están demostrando que son unos verdaderos héroes en la vida real. Te reto a que dibujes a los médicos, enfermeras o personas que se dediquen a cuidar la salud de los mexicanos y nos mandes una foto de tu obra. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/3Kzn-Dr8wtQ',
    }, /*
    38 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    39 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    40 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    41 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    42 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    43 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    22 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    44 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    45 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    25 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    46 : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    }, */
}; 