const vitamin_data = {
    5 : {
        'name' : 'El juego del Aiepo. (Adaptación de la canción de Luis Pescetti)',
        'type' : 'Narración',
        'author' : 'Ana Cristina Ortega, con interpretación en LSM con Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/eAj2wARsYqc',
    },
    53 : {
        'name' : 'Percusiones con vasos de plástico',
        'type' : 'Laboratorio creativo',
        'author' : 'Edith Álvarez Gigi',
        'description' : 'Recomendado para niñas y niños de 6 a 12 años de edad. La música y el canto son un apoyo en el desarrollo del lenguaje, el ritmo y la conciencia corporal.',
        'url' : 'https://www.youtube.com/embed/6f2VPjhRNkM',
    },
    55 : {
        'name' : 'La cabaña del tío Chueco',
        'type' : 'Presentación artística',
        'author' : 'Ramón A Go Gó y Aarón "El Hawaiano"',
        'description' : 'Recomendada para niñas y niños a partir de los 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/hIkdCQA9g1k',
    },    
    64 : {
        'name' : 'La abeja confianzuda',
        'type' : 'Presentación artística',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendada para niñas y niños a partir de los 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/B1m7CufYrJw',
    },
    35 : {
        'name' : 'El elixir del todo: planteamiento',
        'type' : 'Narración',
        'author' : ' Astrid Perellón con interpretación en LSM de Antonio Zacruz.',
        'description' : 'Recomendada para niñas y niños a partir de los 8 años de edad. ',
        'url' : 'https://www.youtube.com/embed/vQxzkTW0ngU',
    },
    82 : {
        'name' : 'Esténcil poético',
        'type' : 'Laboratorio Creativo',
        'author' : 'Jesús Urbina',
        'description' : 'Recomendado para adolescentes a partir de los 13 años de edad. El esténcil es una herramienta que permite la reproducción de una imagen o texto. Se hace uso de una pantalla que delimita el paso de la pintura (o la tinta) por áreas específicas para concretar, a través de un espacio no pintado y un espacio pintado, contrastes en planos, líneas y puntos, con lo cual se genera la imagen. Material: •   Una cartulina partida en cuatro partes, •   Lápiz, goma y sacapuntas •   Cutter y tijeras •   Pintura líquida de colores •   Esponja •   Plato o molde para colocar pintura •   Trapo', 
        'url' : 'https://www.youtube.com/embed/5KeCGwC1SxI',
    }, 
    74 : {
        'name' : 'Juegos corporales',
        'type' : 'Narración',
        'author' : 'Ruth Galicia Islas',
        'description' : 'Recomendada para niñas y niños de 0 a 2 años de edad. Trazado desde el sostén afectivo, tejido con la lírica tradicional latinoamericana, se dan los encuentros familiares. A partir de lecturas de textos, se inicia el encuentro entre los bebés y sus cuidadores. Mirar, leer, cantar y escribir en la piel de los bebés, se da como una forma de cercanía durante los cuidados cotidianos, juego corporal y lírica tradicional. Libros utilizados: ¿Qué te picó la hormiga de los pies a la barriga?, de Isaias Isabel y Pablo Prestifilippo. Editorial CIDCLI Cinco lobitos, de Mercedes Figuerola y Juan Ramón Alonso. Editorial Edelvives Arepita de manteca, de Rosana Faria. Ediciones Ekaré ',
        'url' : 'https://www.youtube.com/embed/PCmOZv74sbY',
    },
    67 : {
        'name' : 'La Tuza',
        'type' : 'Narración',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/UxpamT6V7oM',
    },
    9 : {
        'name' : 'Precisamente Así, de Rudyard Kipling.',
        'type' : 'Narración',
        'author' : 'Ana Cristina Ortega',
        'description' : 'Editorial Juventud. Recomendado para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/3x8VvcbEpi8',
    },
    32 : {
        'name' : 'Juego 1, 2, 3, 4',
        'type' : 'Narración',
        'author' : ' Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 9 años.',
        'url' : 'https://www.youtube.com/embed/HZOwB1JJnR0',
    },
    104 : {
        'name' : 'Sonidos, Ritmo y Reciclado: Maraca',
        'type' : 'Narración',
        'author' : ' Graciela Rodríguez Ramírez',
        'description' : 'Recomendado para niñas y niños a partir de 6 años, acompañados de un adulto. Taller Arte en Cartón- HR (Hermanas Rodríguez), donde los niños y jóvenes puedan ver el reciclado no sólo como una herramienta o insumo, sino como la oportunidad de fomentar su creatividad a través de la elaboración de instrumentos musicales. Al realizar estos instrumentos con reciclado activan sus habilidades manuales y procesos creativos al tiempo que sembrará en ellos el sentido de cooperación en casa y de ayuda con el medio ambiente. Materiales: •   1 botella de PET de 2 litros •   15 taparroscas •   Cinta canela o transparente •   Hojas blancas recicladas •   Pintura acrílica de varios colores •   Pinceles •   Engrudo •   Tijeras •   Cúter •   Regla •   Marcador ',
        'url' : 'https://www.youtube.com/embed/U1HI7gTfA0o',
    },
    59 : {
        'name' : 'Tu ser',
        'type' : 'Presentación artística',
        'author' : ' Vibrá Muchá ',
        'description' : 'Recomendado para adolescentes a partir de 13 años.',
        'url' : 'https://www.youtube.com/embed/2FdwMS7fv2Q',
    }, 
    36 : {
        'name' : 'El elixir del todo. Desarrollo: enemigo',
        'type' : 'Narración',
        'author' : ' Astrid Perellón con interpretación en LSM de Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 8 años.',
        'url' : 'https://www.youtube.com/embed/iBOzQYanCek',
    },
    84 : {
        'name' : 'Haz un amigo',
        'type' : 'Narración',
        'author' : 'Compañía Rima & Drama: José Pablo Coarasa CHXCH y Atza Urieta Garrick',
        'description' : 'Recomendado para niñas y niños a partir de 3 años. ',
        'url' : 'https://www.youtube.com/embed/mEg9kGkX4FQ',
    },
    61 : {
        'name' : 'Puro canto, puro cuento',
        'type' : 'Laboratorio',
        'author' : 'Música de Violeta Durán',
        'description' : 'Recomendado para niñas y niños de 5 años en adelante. A mi Pingo, canción popular Argentina. Textos de cuento y canciones de Rodolfo González.',
        'url' : 'https://www.youtube.com/embed/weXK3AQV_xA',
    }, 
    69 : {
        'name' : 'Fabricación de pelotas caseras para malabares',
        'type' : 'Laboratorio',
        'author' : 'Iván Goycolea',
        'description' : 'Recomendado para niñas y niños a partir de 10 años. Material: Globos del número 9, Semillas de mijo, lentejas (cualquier tipo de semilla semi redonda) sal, o azúcar; Una botella de PET; Un plumón para marcar; Una hoja de papel; Cinta adhesiva; Tijeras de punta roma; Unos calcetines viejos; Piedras o monedas viejas o de 10 pesos. Sinopsis: En este taller aprenderás a elaborar pelotas caseras y reconoceremos algunos elementos de las artes circenses.',
        'url' : 'https://www.youtube.com/embed/8Pocz-TclQQ',
    }, 
    2 : {
        'name' : 'Los monos y la Luna',
        'type' : 'Narración oral',
        'author' : 'Janet Pankowsky',
        'description' : 'Tradición oral del oeste de África. Recomendado para niñas y niños a partir 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/1V_djA9HGQQ',
    }, 
    78 : {
        'name' : 'Tú y un poema spoken word',
        'type' : 'Laboratorio creativo',
        'author' : 'Comikk MG',
        'description' : 'Recomendado para niñas y niños a partir de 10 años de edad. Aprenderás cómo crear un poema libre, en formato spoken word, desde tu experiencia.',
        'url' : 'https://www.youtube.com/embed/wv9ILpQyETg',
    }, 
    42 : {
        'name' : 'La historia del Tecuán',
        'type' : 'Narración oral',
        'author' : 'Kevin Galeana y Antonio Cruz',
        'description' : 'Tradición oral del estado de Guerrero. Con interpretación en Lengua de Señas Mexicana. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/6Zw050k_MEQ',
    }, 
    37 : {
        'name' : 'El elixir del todo. Posible desarrollo 1: aliado',
        'type' : 'Narración oral',
        'author' : ' Astrid Perellón y Antonio Zacruz',
        'description' : 'Con interpretación en Lenguas de Señas Mexicano. Recomendado para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/49Y5N6UIu-8',
    },
    129 : {
        'name' : 'Click. (Primera parte)',
        'type' : 'Presentación artística',
        'author' : ' Sopa de Clown',
        'description' : 'Recomendado para niñas y niños a partir de 3 años. En tiempos de selfies, seguramente tienes más de 20 fotos iguales en tu celular y solo tú reconoces cuál es la mejor. Así como tú, Tita y Nubi, un par de simpáticas clowns ocurrentes y juguetonas están dispuestas a tomarse la mejor foto.',
        'url' : 'https://www.youtube.com/embed/bwu2s57wB44',
    }, 
    38 : {
        'name' : 'El elixir del todo. Posible desarrollo 1: pruebas',
        'type' : 'Narración oral',
        'author' : ' Astrid Perellón y Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad. Con interpretación en Lengua de Señas Mexicana.',
        'url' : 'https://www.youtube.com/embed/PLJj2jgx1U0',
    },
    108 : {
        'name' : 'El niño y el tiburón',
        'type' : 'Presentación Artística',
        'author' : ' Ramón A Go Go y Aarón El Hawaiano',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/f9OhcqRUcwg',
    },
    70 : {
        'name' : 'Trucos básicos de malabares con tres pelotas',
        'type' : 'Laboratorio creativo',
        'author' : ' Iván Goycolea',
        'description' : 'Recomendado para niñas y niños a partir de 10 años de edad. En este taller realizaremos el truco básico de malabares, haremos algunos ejercicios que desafiarán la gravedad y nos divertiremos con las pelotas que fabricamos en la Cápsula 68.',
        'url' : 'https://www.youtube.com/embed/WXqwXbbTmqw',
    },
    57 : {
        'name' : 'Dos Vidas. Música',
        'type' : 'Presentación artística',
        'author' : ' Ro Aguilar, integrante del grupo Quiroga',
        'description' : 'Recomendado para niñas y niños a partir de 11 años',
        'url' : 'https://www.youtube.com/embed/nrVHHO-qHt4',
    },
    85 : {
        'name' : 'Arrullos y apapachos: primeros cuidados',
        'type' : 'Laboratorio',
        'author' : ' Lilian Cantante',
        'description' : 'Recomendado para niñas y niños de 3 a 5 años de edad. Dodi pío necesita cuidados, una casita, comida, cobija, cariño ¡y le gustan mucho las canciones! Materiales: • 1 calcetín amarillo. • 1 pelota de plástico pequeña. • 2 ligas chiquitas. • 1 trozo de foamy negro. • 1 trozo de fieltro color carne. • 1 perforadora de mano. • Tijeras. • 1 botella pequeña de silicón frío. • 4 limpiapipas de colores.  • 1 toallita facial de bebé. • 1 cajita de cartón pequeña con tapa.',
        'url' : 'https://www.youtube.com/embed/jQlV8oHW4ao',
    },
    51 : {
        'name' : 'Dedikos: títeres para dedos',
        'type' : 'Laboratorio Creativo',
        'author' : ' Edith Álvarez Gigi',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/LU-PPi6SdOc',
    },
    3 : {
        'name' : 'Rimas del Sol',
        'type' : 'Narración oral',
        'author' : ' Janet Pankowsky',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/r7y8GLc9sKE',
    }, 
    122 : {
        'name' : 'Love Me Twice / Ámame dos veces (música)',
        'type' : 'Presentación artística',
        'author' : ' Béke',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/OesSyCD694s',
    },  
    72 : {
        'name' : 'Lectura del libro: Ardilla miedosa',
        'type' : 'Narración oral',
        'author' : ' Ruth Galicia Islas',
        'description' : 'Libro de Melanié Watt. Editorial SM. Recomendada para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/3ts-BWpXXmU',
    },    
    94 : {
        'name' : 'La búsqueda del tesoro',
        'type' : 'Laboratorio creativo ',
        'author' : 'Ana Zarina',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/nvXRYdunuQc',
    },
    109 : {
        'name' : 'Jonás y la ballena',
        'type' : 'Presentación artística',
        'author' : 'Ramón A Go Go y Aarón El Hawaiano',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/RIoIvGwfDP8',
    },
    15 : {
        'name' : 'Yo no soy un conejo',
        'type' : 'Narración oral',
        'author' : 'Lidia Zaragoza',
        'description' : 'Basada en el libro "Yo no soy un conejo" de Pepe Márquez y Natalia Colombo. Fondo de Cultura Económica, colección Los primerísimos. Recomendado para niñas y niños a partir 5 años de edad.',
        'url' : 'https://www.youtube.com/embed/NX3e9zQsk8s',
    },
    39 : {
        'name' : 'El elixir del todo: El gran final',
        'type' : 'Narración oral',
        'author' : 'Astrid Perellón y Antonio Zacruz',
        'description' : 'Original de Astrid Perellón, con interpretación en Lengua de Señas Mexicana. Recomendado para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/M3Z-9OHwmR0',
    },
    91 : {
        'name' : 'Máscara de jaguar sobre paisaje',
        'type' : 'Laboratorio creativo',
        'author' : 'Manuel Reyes Tissera',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Materiales: dos hojas blancas de papel tamaño carta. Cinta adhesiva de cualquier tipo. Cinco plumones de colores, de preferencia, de punta delgada.',
        'url' : 'https://www.youtube.com/embed/wryTF7xR6jE',
    },
    113 : {
        'name' : 'El piojo',
        'type' : 'Presentación artística',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/sDEheJNi-ts',
    },
    77 : {
        'name' : 'Trucos de malabares con 3 y 4 pelotas',
        'type' : 'Laboratorio creativo',
        'author' : 'Iván Goycolea',
        'description' : 'Recomendado para niñas y niños a partir de 10 años de edad.',
        'url' : 'https://www.youtube.com/embed/xIW8lMwrzy8',
    },
    10 : {
        'name' : 'Trucas',
        'type' : 'Narración oral',
        'author' : 'Raúl Pérez Buendía',
        'description' : 'Basada en el libro Trucas, de Juan Gedovius. Fondo de Cultura Económica. Recomendado para niñas y niños a partir 5 años de edad.',
        'url' : 'https://www.youtube.com/embed/23rJibMiMo4',
    },
    128 : {
        'name' : 'Tu lugar',
        'type' : 'Presentación artística',
        'author' : 'Orquesta Basura',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/x8fDo3i7rsM',
    },  
    50 : {
        'name' : 'Cantos y juegos: Un sapito',
        'type' : 'Narración oral',
        'author' : 'Edith Álvarez Gigi',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/kOI3PD_RDII',
    },  
    43 : {
        'name' : 'Bemberecua',
        'type' : 'Narración oral',
        'author' : 'Kevin Galeana y Antonio Zacruz',
        'description' : 'Basada en Bemberecua de Honorio Robledo. Editado por Artes de México. Con interpretación en Lengua de Señas Mexicana. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/WpJ5JkCosEs',
    },
    130 : {
        'name' : 'Click. (Segunda parte)',
        'type' : 'Presentación artística',
        'author' : 'Sopa de Clown',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/cz_1jiB05LA',
    },  
    58 : {
        'name' : 'María Cirila',
        'type' : 'Presentación artística',
        'author' : 'Vibra Muchá',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/SStwXbeYlsU',
    },  
    47 : {
        'name' : 'El ratón que comía gatos',
        'type' : 'Narración oral',
        'author' : 'Ángel Aranda',
        'description' : 'Basado en el cuento "El ratón que comía gatos", de Gianni Rodari. Editorial Juventud. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/miO45qT0Kf8',
    },
    124 : {
        'name' : 'Jack y la muerte (fragmento de la obra "Nocturnos")',
        'type' : 'Narración oral',
        'author' : 'Compañía Laboratorio Mecánica en Miniatura',
        'description' : 'Teatro de títeres. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/ftYDPaF-H0w',
    },
    87 : {
        'name' : 'Vacaciones en familia: Día de pesca en la playa',
        'type' : 'Narración oral',
        'author' : 'Lilian Cantante',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/nVGA5EW9UZM',
    },
    101 : {
        'name' : 'Nano rap',
        'type' : 'Narración oral',
        'author' : 'Sergio Ferrer',
        'description' : 'Recomendado para niñas y niños a partir de 7 años de edad.',
        'url' : 'https://www.youtube.com/embed/vub95CUSRCc',
    },
    68 : {
        'name' : 'Moby Dick',
        'type' : 'Presentación artística',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/oxyqAoE6iXs',
    },
    45 : {
        'name' : 'Kevin Galeana recomienda: Monstruos mexicanos',
        'type' : 'Fomento a la lectura',
        'author' : 'Kevin Galeana',
        'description' : 'Para niñas y niños a partir de 8 años de edad. "Monstruos Mexicanos" de Carmen Leñero. Ilustraciones: Kamui Gomasio y Marcos Castro. Editorial: Alas y Raíces. Año de edición: 2019. El miedo, ese frío que aparece de repente adentro de los huesos y hace pelar los ojos. ¿Qué es eso que se mueve entre las sombras? ¿Por qué a las niñas y los niños les atraen los monstruos, si son tan horripilantes y perversos? Si te gustan las historias de susto, este libro es para ti, pues en él encontrarás algunas de estas criaturas, las que nacieron y viven en México. Serpiente de fuego, Aluxes, Chaneques, Tukákame, Serpiente Tsukán, el Sinsimio, el Waay Chivo y la Serpiente de siete cabezas son algunos de los monstruos que aquí presentamos, con todos los detalles que debes tener a la mano sobre ellos. Descarga el libro en PDF en www.alasyraices.gob.mx/ebooks.html',
        'url' : 'https://www.youtube.com/embed/awbIN8sCgJg',
    },  
    46 : {
        'name' : 'Semillas de tinta',
        'type' : 'Fomento a la lectura',
        'author' : 'Antonio Zacruz',
        'description' : 'Para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/oNFu741vAws',
    },
    105 : {
        'name' : 'Sonidos, ritmo y reciclado: Tambor',
        'type' : 'Laboratorio creativo',
        'author' : 'Roberto Gutiérrez Vega',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad, acompañados de un adulto. Taller Arte en Cartón- HR (Hermanas Rodríguez), donde los niños y jóvenes puedan ver el reciclado no sólo como una herramienta o insumo, sino como la oportunidad de fomentar su creatividad a través de la elaboración de instrumentos musicales. Al realizar estos instrumentos con reciclado activan sus habilidades manuales y procesos creativos al tiempo que sembrará en ellos el sentido de cooperación en casa y de ayuda con el medio ambiente. Materiales: Un bote de metal o plástico duro (no importa el tamaño). Dos palitos de madera redondos de 20 cm. Un pedacito de tela. Listones, agujetas o ligas de colores (opcional). Silicón líquido. Cinta canela o transparente. Hojas blancas recicladas. Pintura acrílica. Pinceles. Engrudo. Tijeras. Regla. Lápiz. ',
        'url' : 'https://www.youtube.com/embed/8PIjnoLQRew',
    },
    28 : {
        'name' : 'Gastronomía',
        'type' : 'Laboratorio creativo',
        'author' : 'Omar Ramírez',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad. Mediante pasos sencillos, el chef Omar Ramírez, te lleva de la mano para elaborar dos menús completos de comida mexicana, utilizando ingredientes que puedes encontrar en el mercado de tu localidad.',
        'url' : 'https://www.youtube.com/embed/i6JIJjyd3Us',
    },
    131 : {
        'name' : 'Click. (Tercera parte). Teatro clown',
        'type' : 'Presentación artística',
        'author' : 'Sopa de Clown',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/ARR1CXMa0z4',
    },
    99 : {
        'name' : 'Flipbook. Anima tu aventura',
        'type' : 'Laboratorio creativo',
        'author' : 'Mariana Córdova',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/eOjBLgdsomI',
    },  
    114 : {
        'name' : 'El Cascabel',
        'type' : 'Presentación artística',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/YPbDo5tothU',
    },
    13 : {
        'name' : 'Raúl Pérez Buendía recomienda Luna sandía',
        'type' : 'Fomento a la lectura',
        'author' : 'Raúl Pérez Buendía',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. "Luna Sandía. Treinta sueños extraordinarios de niñas y niños mexicanos". Compilador: Roger Omar. Ilustradores: Jimena Estíbaliz, Daniela Martín del Campo, Pamela Medina, Gala Navarro, Mariana Roldán y Manuel Vargas. Editorial: Alas y Raíces. Año de edición: 2019. Soñar que eres raptado por los extraterrestres o que tu cama está en medio de un volcán; cosas extraordinarias y sueños muy alocados es lo que encontrarás en este libro. "Luna Sandía" ilustra sueños extraordinarios de niñas y niños de todo México.',
        'url' : 'https://www.youtube.com/embed/sNmf32yhi6U',
    },
    142 : {
        'name' : 'Dibujando nuestros miedos',
        'type' : 'Laboratorio creativo',
        'author' : 'Francisco González',
        'description' : 'Recomendado para niñas y niños a partir de 9 años de edad. ¿Tú a qué le tienes miedo? ¿de dónde viene ese miedo? A partir de El libro valiente descubriremos en esta cápsula que nuestra familia, aunque sean personas adultas, también tienen miedos, por lo que para conocerlos les haremos a una breve entrevista para que después podamos dibujar ese miedo y, con su ayuda, darle color. Materiales: Un cuaderno. Pluma o lápiz. Hojas blancas. Lápices de colores y/o marcadores ',
        'url' : 'https://www.youtube.com/embed/uWuJIca9ZeI',
    },
    96 : {
        'name' : 'Maj xikchisej totletenewalistonal / Sembremos nuestro tonal',
        'type' : 'actividad',
        'author' : 'Edgar Tochtli',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Taller donde podremos conocer una de las lenguas originarias de México, la lengua náhuatl. Conoceremos el tonal, una de las tradiciones del pueblo Náhuatl y haremos nuestro propio tonal. Materiales: Cartulina. Hojas de colores. Pegamento en barra. Tijeras. Lápiz. Plumones de colores ',
        'url' : 'https://www.youtube.com/embed/XRekatLtjTk',
    },
    66: {
        'name' : 'Mi papá es rocanrolero',
        'type' : 'Narración oral',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. "Los Botes Cantan" siguen sorprendiendo a las infancias con canciones muy divertidas, que pueden bailar o solo escuchar en casa. Esta vez Pedro Sandoval, vocalista del grupo, nos presenta sus canciones más escuchadas, pero en una versión acústica. Canción que forma parte del disco "Diez".',
        'url' : 'https://www.youtube.com/embed/DzE-KqApMzc',
    },
    97 : {
        'name' : 'Palabras como ramas: Cómo escribir poemas al 2 x 1',
        'type' : 'Laboratorio creativo',
        'author' : 'Cynthia Franco',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad. En este taller aprenderemos que escribir poesía es el antídoto contra el aburrimiento, que poner el lápiz en la hoja está en favor de las lágrimas, la risa, la alegría y la vida misma. Incluso, para crear nuevos mundos, cuando escribo, me atrevo, imagino lo que quiero. Materiales: Hojas recicladas. Lápices. Colores.',
        'url' : 'https://www.youtube.com/embed/clWotAVYdcE',
    },
    136 : {
        'name' : '¿Para qué nos sirven los miedos?',
        'type' : 'Laboratorio creativo',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. A partir de la narración de un fragmento de "El libro valiente" de Moni Port, editorial Takatuka, niñas y niños cantarán una canción que los invita a seguir un juego y bailar a partir de una coreografía. La canción cuenta la historia de una bruja que ya nadie le tenía miedo, llamada: "La verruga de la vieja bruja".',
        'url' : 'https://www.youtube.com/embed/eKK6Kur78KI',
    },
    133 : {
        'name' : 'Malabares con frutas: Desmenuzando el Delirio Culinario (Primera parte). (Arte Circense)',
        'type' : 'Presentación artística',
        'author' : 'Compañía Circonciente',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Giorgo Peperonne, el chef de fama internacional, trae para nosotros recetas para hacer en casa; sólo se necesitan limones o naranjas, así de fácil, bueno, cada receta va subiendo grados de dificultad, pero con mucha práctica en casa, seguro lo lograrás.',
        'url' : 'https://www.youtube.com/embed/jyfYLyYIo1U',
    },
    89 : {
        'name' : 'Danae Servin recomienda "Las horas para siempre"',
        'type' : 'Fomento a la lectura',
        'author' : 'Danae Servin',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad. "Las horas para siempre". Antología de la colección “Poesía para niños”. Autores: Ramón López Velarde, Carlos Pellicer, Elías Nandino, Efraín Huerta, Octavio Paz, Jaime Sabines y Enriqueta Ochoa. Ilustraciones: Niñas y niños del ala de Oncología del Centro Médico Nacional 20 de Noviembre. Editorial: Alas y Raíces. Año de edición: 2018. La colección "Poesía para niños" es uno de los proyectos editoriales del sello Alas y Raíces. En esta ocasión, "Las horas para siempre" reúne la poesía de reconocidos autores mexicanos, como Octavio Paz, Ramón López Velarde, Carlos Pellicer, Enriqueta Ochoa, Elías Nandino, Efraín Huerta y Jaime Sabines, cuyos versos fueron ilustrados por niñas y niños del ala de Oncología del Centro Médico Nacional 20 de Noviembre.',
        'url' : 'https://www.youtube.com/embed/kFnKzEtNg_o',
    },
    60 : {
        'name' : 'Las frutas',
        'type' : 'Presentación artística',
        'author' : 'Vibra Muchá',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Conoce el reggaeson, música reggae fusionada con tintes soneros, creación original del grupo Vibra Muchá, pioneros también en dirigir este género para las infancias, con la fuerte convicción de llevar su música a todas las personas.',
        'url' : 'https://www.youtube.com/embed/_EmL9iE4kCI',
    },
    95 : {
        'name' : 'De viaje por nuestra casa',
        'type' : 'Laboratorio creativo',
        'author' : 'Ana Zarina',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Diseñaremos el mapa de un recorrido turístico virtual por nuestra localidad, apoyándonos con fotografías, postales u objetos que la representen.',
        'url' : 'https://www.youtube.com/embed/C0w55V_xP2I',
    },
    6: {
        'name' : 'El quetzal, mito de tradición oral',
        'type' : 'Narración oral',
        'author' : 'Ana Cristina Ortega y Antonio Zacruz ',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad. Con interpretación en Lengua Mexicana de Señas. Cuentan en el sureste de México una historia que narra cómo eran las aves antes de que fueran como las conocemos. Ana Cristina Ortega y Antonio Zacruz nos cuentan cómo fue que antes, mucho antes, cuando las aves no podían ni volar, con la ayuda de un quetzal el dios Chaac las pudo transformar.',
        'url' : 'https://www.youtube.com/embed/2gbZunoOCIs',
    },
    118 : {
        'name' : 'Emptiness / Vacío',
        'type' : 'Presentación artística',
        'author' : 'Béke',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/Qw8Ii1v7DCo',
    },  
    16 : {
        'name' : 'El castillo de Cucuruchá',
        'type' : 'Narración oral',
        'author' : 'Lidia Zaragoza',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad. Basada en el libro "Así cantan y juegan en La Huasteca". Editado por CONAFE.',
        'url' : 'https://www.youtube.com/embed/vc8c8tuGJss',
    },
    92 : {
        'name' : 'Pteranomóvil',
        'type' : 'Laboratorio creativo',
        'author' : 'Manuel Reyes Tissera',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/lEGY5ea9ClA',
    },  
    145 : {
        'name' : 'Collage',
        'type' : 'Laboratorio creativo',
        'author' : 'Francisco González',
        'description' : 'Recomendado para niñas y niños a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/0rlmy4y8C1I',
    },
    4 : {
        'name' : 'Trabalenguas de dragones ',
        'type' : 'Fomento a la lectura',
        'author' : 'Janet Pankowsky',
        'description' : 'Recomendado para niñas y niños a partir de 9 años de edad. Recomendación del libro "El Jinete del Dragón" de Cornelia Funke. Editorial Fondo de Cultura Económica.',
        'url' : 'https://www.youtube.com/embed/S8ej0Dmgj5M',
    },  
    23 : {
        'name' : 'Eslam de Poesía',
        'type' : 'Narración oral',
        'author' : 'Rojo Córdova',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/Unn9hcfpFX4',
    },
    86 : {
        'name' : 'Arrullos y apapachos: El juego del pin, pon, papas',
        'type' : 'Narración oral',
        'author' : 'Lilian Cantante',
        'description' : 'Recomendado para niñas y niños a partir de 0 años de edad.',
        'url' : 'https://www.youtube.com/embed/vw400cTR0YQ',
    }, 
    1 : {
        'name' : 'Un lunes por la mañana',
        'type' : 'Actividad',
        'author' : 'Janet Pankowsky',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad. Basada en Un lunes por la mañana de Uri Shulevitz. Editorial Fondo de Cultura Económica.',
        'url' : 'https://www.youtube.com/embed/FkYbNV28mXE',
    },
    83 : {
        'name' : 'Encuadernación plegable',
        'type' : 'Actividad',
        'author' : 'Jesús Urbina',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/7kdO0uTUkhs',
    }, 
    100 : {
        'name' : 'Desde mi casa',
        'type' : 'Música',
        'author' : 'Pepe Frank',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/mArYnUZWuQA',
    },
    49 : {
        'name' : 'Teatrino de sombras',
        'type' : 'Actividad',
        'author' : 'Edith Álvarez Gigi',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/UU0LcuHSH5c',
    },
    90 : {
        'name' : 'Martín Arias recomienda: Cuando hablaba era contigo',
        'type' : 'Fomento a la lectura',
        'author' : 'Martín Arias',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/l3YdVLBRLPo',
    }, 
    116 : {
        'name' : 'La bamba',
        'type' : 'Música',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/C48sJ3a7h38',
    },
    148 : {
        'name' : 'Desayunando Versos',
        'type' : 'Presentación artística',
        'author' : 'Staku Allende',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/8mUKbfiw-9g',
    }, 
    143 : {
        'name' : 'Creación de una máscara contra el miedo',
        'type' : 'Actividad',
        'author' : 'Francisco González',
        'description' : 'Recomendado para niñas y niños a partir de 9 años de edad.',
        'url' : 'https://www.youtube.com/embed/QyFb2f5gv9k',
    },
    65 : {
        'name' : 'Ícaro',
        'type' : 'Música',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/xc_gmgHGP7M',
    },
    17 : {
        'name' : 'Lidia Zaragoza y Antonio Zacruz recomiendan: Cuando nos hayamos comido el planeta',
        'type' : 'Fomento a la lectura',
        'author' : 'Lidia Zaragoza y Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/z2lmDUAQYTA',
    },
    140 : {
        'name' : 'La canción de Emma',
        'type' : 'Actividad Primera Infancia',
        'author' : 'Tanya Covarrubias',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/cM_NyWYC88U',
    },
    24 : {
        'name' : 'Hip hop Dance',
        'type' : 'Laboratorio Creativo',
        'author' : 'Funky Maya',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/YhCSErL2XBU',
    }, 
    125 : {
        'name' : 'Construcción de kazoo (mosca)',
        'type' : 'Laboratorio creativo',
        'author' : 'Yayo Basura. Orquesta Basura',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad, con supervisión de un adulto.',
        'url' : 'https://www.youtube.com/embed/GSnyjCmpxAo',
    },
    123 : {
        'name' : 'Backtrack / Retroceder',
        'type' : 'Música',
        'author' : 'Béke',
        'description' : 'Recomendado para  adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/mbVERmF_hqU',
    }, 
    111 : {
        'name' : 'Ardo',
        'type' : 'Actividad',
        'author' : 'Ro Aguilar, integrante del grupo Quiroga',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/2HaZQD2hVPU',
    },
    75 : {
        'name' : 'Arrullarte: Lunas y arrullos',
        'type' : 'Actividad',
        'author' : 'Ruth Galicia Islas',
        'description' : 'Recomendado para niñas y niños  de 0 a 2 años años de edad.',
        'url' : 'https://www.youtube.com/embed/XbAfudBxgrQ',
    }, 
    33 : {
        'name' : 'Juego: Los pasos del abuelo',
        'type' : 'Narración',
        'author' : 'Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 9 años de edad.',
        'url' : 'https://www.youtube.com/embed/ips6vzerLSA',
    }, 
    134 : {
        'name' : 'Malabares con frutas: Desmenuzando el Delirio Culinario (Segunda parte)',
        'type' : 'Arte circense',
        'author' : 'Compañía Circonciente',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/noZjuyQRtf0',
    }, 
    144 : {
        'name' : 'Un cuento fantástico',
        'type' : 'Laboratorio creativo',
        'author' : 'Francisco González',
        'description' : 'Recomendado para niñas y niños a partir de 9 años de edad.',
        'url' : 'https://www.youtube.com/embed/wmFcxoX-nFE',
    }, 
    44 : {	
        'name' : 'Nelson Mandela',
        'type' : 'Fomento a la Lectura',
        'author' : 'Astrid Perellón y Kevin Galeana',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad.',
        'url' : 'https://www.youtube.com/embed/97pQ2GXaMQg',
    },
    132 : {
        'name' : 'Vals de los calcetines',
        'type' : 'Presentación artística: Música',
        'author' : 'Fores Basura',
        'description' : 'Recomendado para niñas y niños a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/TRKRs76LlGo',
    }, 
    63 : {
        'name' : 'Ayer salí de sexto',
        'type' : 'Presentación artística: Música',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/sYBRUJgc1rI',
    }, 
    106 : {
        'name' : 'Álbum, memoria y exposiciones: Álbum fotográfico',
        'type' : 'Laboratorio creativo',
        'author' : 'Sandra Gasca Rodríguez',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/JIY5X0-2nJc',
    }, 
    121 : {
        'name' : 'The Urge / La urgencia',
        'type' : 'Presentaciones artísticas',
        'author' : 'Béke',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/QYG2kWUU5po',
    },
    30 : {
        'name' : 'Tutorial huerto',
        'type' : 'Laboratorio creativo',
        'author' : 'Piero V',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad.',
        'url' : 'https://www.youtube.com/embed/MT4aWEm3jOM',
    }, 
    138 : {
        'name' : 'Sensación y emoción',
        'type' : 'Actividad',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto', 
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Basado en "El libro valiente" de Moni Port, Editorial Takatuka.',
        'url' : 'https://www.youtube.com/embed/5yQWW_iZ9Ps',
    },
    14 : {
        'name' : 'El gato, son de tarima de Tixtla, Guerrero',
        'type' : 'Narraciones orales',
        'author' : 'Lidia Zaragoza',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/JrZXQ4-GCww',
    }, 
    102 : {
        'name' : 'Sonidos, ritmo y reciclado: Palo de lluvia (Taller)',
        'type' : 'Actividad',
        'author' : 'Araceli Rodríguez Ramírez',
        'description' : 'Recomendado para niñas y niños a partir de 6 años, acompañados de un adulto. Materiales: Un tubo de cartón de papel absorbente (servi-toallas) o 2 tubos de papel de baño. • Una hoja de periódico recortada o desgarrada en tiras. • Cartón de caja cereal • Silicón líquido • 30 clavos de 2.5 cm. • Masking tape• Engrudo • Semillas (frijol, arroz, lenteja) • Pintura acrílica blanca • Pintura acrílica de color • Un pedacito de lazo o estambre • Tijeras • Pincel • Regla • Lápiz. Taller Arte en Cartón- HR (Hermanas Rodríguez), donde los niños y jóvenes puedan ver el reciclado no sólo como una herramienta o insumo, sino como la oportunidad de fomentar su creatividad a través de la elaboración de instrumentos musicales. Al realizar estos instrumentos con reciclado activan sus habilidades manuales y procesos creativos al tiempo que sembrará en ellos el sentido de cooperación en casa y de ayuda con el medio ambiente.',
        'url' : 'https://www.youtube.com/embed/t2XtzXyoU-o',
    },
    12: {
        'name' : 'Del otro lado del árbol y Un grande y rojo dragón',
        'type' : 'Narración oral',
        'author' : 'Raúl Pérez Buendía',
        'description' : 'Basadas en el libro "Del otro lado del árbol" de Mandana Sadat. Editoral Fondo de Cultura Económica y en "Un grande y rojo dragón" de Raúl Pérez Buendía. Inédito. Recomendado para niñas y niños a partir de 6 años de edad. Una tarde, Mandana descubrió una casita del otro lado del árbol; una casita que nunca había visto antes. Guiada por la curiosidad, decidió acercarse para descubrir que la escoba en la puerta, el cuervo que revoloteó y la luz de una vela iluminando el interior, sólo podían significar una cosa: esa era la casa de ¡una bruja!',
        'url' : 'https://www.youtube.com/embed/JdSJxT9mp3E',
    },
    117 : {
        'name' : 'La iguana',
        'type' : 'Presentación artística, música',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. La iguana forma parte de su concierto “Ay que sí que sí que no” donde se recrea la historia de la tradición musical campesina del sur de Veracruz, repleta de sones jarochos que se destacan por su fina y bella poesía, además de un buen zapateado que niñas y niños pueden bailar en casa.',
        'url' : 'https://www.youtube.com/embed/B-Zngo43wZk',
    },  
    81 : {
        'name' : 'Libro magicollage',
        'type' : 'Laboratorio creativo',
        'author' : 'Jesús Urbina',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad. Este taller fomenta la exploración y libertad artística y creativa de niñas y niños, al permitirles crear poemas visuales con la técnica de collage, a la par que van creando pequeños libros de artista en formatos plegables, que pueden ser doblados y desdoblados para ir pasando entre las páginas. Materiales: • Hojas tamaño carta, de colores • Tijeras • Pegamento en barra • Lápices y plumones colores • Revistas para recortar.',
        'url' : 'https://www.youtube.com/embed/0fi4HyvgzEg',
    },
    146 : {
        'name' : 'Personajes fantásticos',
        'type' : 'Laboratorio Creativo',
        'author' : 'Francisco González',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad. En esta cápsula haremos un personaje fantástico con súper poderes, puede ser una persona, un animal o puedes crearlo como tú desees, también tienes que pensar cuál será ese súper poder que te ayudará a derribar tus miedos. Materiales: • Un cuaderno • Pluma • Hojas blancas • Lápices de colores y/o marcadores',
        'url' : 'https://www.youtube.com/embed/uDdGC3uLkgs',
    },
    8 : {
        'name' : 'Donde viven los monstruos',
        'type' : 'Narración oral y en LSM',
        'author' : 'Ana Cristina Ortega y Antonio Zacruz',
        'description' : 'Basada en el libro: "Donde viven los monstruos" de Maurice Sendak. Editorial Alfaguara. Con interpretación en Lengua de Señas Mexicana. Recomendado para niñas y niños a partir de 5 años de edad. Max, un niño muy travieso ha hecho la travesura más grande, la más monstruosa, y por eso, ha tenido que ir a visitar una isla misteriosa: el lugar donde viven los monstruos. ¿Quieres saber qué pasó cuando Max y los monstruos se miraron a los ojos? Ana Cristina Ortega y Antonio Zacruz nos lo van a contar en esta es una divertida versión.',
        'url' : 'https://www.youtube.com/embed/Qr7X5IxlRqA',
    }, 
    54 : {
        'name' : 'Pollito',
        'type' : 'Presentación artística: música',
        'author' : 'Ramón A Go Go y Aarón El Hawaiano',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Ramón, un ukulele y rock con tintes hawaianos, son la mezcla perfecta para que brinques cómo chapulín con muchas canciones que te harán reír y disfrutar estos ritmos pegajosos que traen para ti.',
        'url' : 'https://www.youtube.com/embed/MSrb61Bi8Yo',
    },
    62 : {
        'name' : 'Puro Canto, Puro Cuento',
        'type' : 'Presentaciones artísticas: Música',
        'author' : 'Puro Canto, Puro Cuento',
        'description' : 'Textos de cuento y canciones de Rodolfo González, Música de Violeta Durán. Recomendado para niñas y niños a partir de 5 años de edad. "Puro Canto, Puro Cuento" es un grupo de música tradicional que trae para ti muchas historias, algunas serán acompañadas por Artemio, un niño muy curioso, que así como tiene muchas dudas, sabe muchas cosas.',
        'url' : 'https://www.youtube.com/embed/MTsBJj2JEiQ',
    },
    126 : {
        'name' : 'Fores Basura',
        'type' : 'Laboratorio creativo para la elaboración de instrumento musical: Gallina',
        'author' : 'Orquesta Basura',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad, con supervisión de un adulto. Materiales: • Un vaso de plástico desechable • Hilo grueso • Palillo de madera • Compás, puede ser incluso un clavo, lo que se necesita es una punta redonda que pueda hacer un orificio en el vaso de plástico. • Regla • Tijeras • Calcetín limpio. Si te gusta imitar sonidos de animales, este tutorial es perfecto para ti; imagina qué chistoso suena el graznar de una gallina, ahora imagina ese sonido saliendo de un vaso con un hilo, ya lo hiciste ¿verdad? Bueno, ahora sólo te falta construir el instrumento musical, checa este tutorial facilísimo y grazna como gallina por toda tu casa.',
        'url' : 'https://www.youtube.com/embed/lG6AE_Mz_0M',
    }, 
    149 : {
        'name' : 'El viejito del sillón',
        'type' : 'Narración oral',
        'author' : 'Marcela Romero',
        'description' : 'Basada en "El viejito del sillón" de Antonio Orlando Rodríguez, Editorial El Naranjo. Recomendada para niñas y niños a partir de 6 años de edad. Cuenta la historia que una vez llegó un viejito a un pequeño pueblo, se instaló en una casa pequeña blanca. Dicen que, todos los días antes de que cayera la tarde, ese viejito sacaba de su casa una mecedora y se sentaba a gusto a ver cómo el cielo se teñía de rojo, naranja, amarillo… ¿Quieres saber qué hacía ese viejito sentado en su mecedora?',
        'url' : 'https://www.youtube.com/embed/aa7Mi2PT44o',
    },
    141 : {
        'name' : '¿Cuándo has sido valiente?',
        'type' : 'Actividad',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto',
        'description' : 'Basado en "El libro valiente" de Moni Port, editorial Takatuka. Recomendado para niñas y niños a partir de 3 años de edad. En este video conocerás una canción que habla sobre valentía, niñas y niños podrán cambiar algunas palabras para adaptarla y contar su propia historia, verán que cuando se es valiente resulta muy fácil componer canciones.',
        'url' : 'https://www.youtube.com/embed/VbC_-Rkj-2k',
    },    
    151 : {
        'name' : '¡Dibuja, juega y canta tu propia lotería de animales!',
        'type' : 'Laboratorio creativo',
        'author' : 'Alec Dempster',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Durante este taller vamos a crear un juego de lotería con sones jarochos que nombran 16 animales. Vamos a escuchar los sones y hacer cuatro cartones. También haremos las 16 cartas donde va el nombre del animal y el verso que se canta al "gritar" la loteríaaaaaaaaaaa. Materiales: • Cinco hojas blancas de tamaño carta. • Lápiz • Lápices de colores, plumones o pintura • Borrador • Tijeras',
        'url' : 'https://www.youtube.com/embed/3ffT1l0LQDE',
    },
    155 : {
        'name' : 'Cántaro ',
        'type' : 'Presentación artística',
        'author' : 'Tema de Cántaro',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Con una sonrisa todo sale mucho mejor. Así Lore y Chepo te cantarán algo muy cierto; todo cabe en un juego si lo sabes acomodar; platicar con elefantes, saltar con un chapulín y muchas más cosas que puedas imaginar.',
        'url' : 'https://www.youtube.com/embed/F5lLITlFg6U',
    }, 
    153 : {
        'name' : 'Cuentos emplumados',
        'type' : 'Narración oral',
        'author' : 'Yademira Barragán',
        'description' : 'Recomendado para niñas y niños a partir de 12 años de edad. Cuento de un pájaro singular que colorea el paisaje a través de la voz de la narradora, que extiende sus alas para compartir sus vuelos por las tradiciones orales de los indios de América.',
        'url' : 'https://www.youtube.com/embed/WZZFiBs5Gfg',
    }, 
    147 : {
        'name' : 'Escultura de la Valentía',
        'type' : 'Laboratorio creativo',
        'author' : 'Francisco González',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad. ¿Qué me hace ser valiente? A partir de recordar una anécdota en la que hayas enfrentado el miedo y cómo lo superaste, haremos una escultura de la valentía. Esta escultura será tridimensional con plastilina y otros objetos. Materiales: • Una hoja blanca • Lápiz • Una barra de plastilina',
        'url' : 'https://www.youtube.com/embed/6zYDdeL-skU',
    },
    154 : {
        'name' : 'Jugando entre canciones y palabras',
        'type' : 'Narración oral y música',
        'author' : 'Kevin Galeana',
        'description' : 'Recomendado para niñas y niños a partir de 12 años de edad. Narración oral y música que propone jugar, cantar y contar como un ejercicio de libertad.',
        'url' : 'https://www.youtube.com/embed/UkgoLsOP1tE',
    },  
    158 : {
        'name' : 'Conociendo la trompeta',
        'type' : 'Presentación artística',
        'author' : 'José Lara Gaytán, trompetista de La Pingo’s Orquesta',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. La Pingo´s Orquesta es una agrupación musical mexicana de World Music formada en el año 2012 en Aguascalientes, México. La propuesta musical de la banda implica la fusión de diversos géneros y estilos como la Música Clásica, el Jazz Manouche, el Swing, Tango, la Música Balcánica y el Folclor Latinoamericano. En sus temas, logran plasmar todo el bagaje musical de cada uno de sus integrantes definiéndose como una diversidad de estilos en una colorida propuesta.',
        'url' : 'https://www.youtube.com/embed/s6or2O0N01M',
    },
    157 : {
        'name' : 'Títere de papel',
        'type' : 'Actividad',
        'author' : 'Arlen Larios',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Materiales: • Hojas de papel blancas o de colores • Cinta adhesiva • Tijeras • Marcadores, plumones o lápices de colores',
        'url' : 'https://www.youtube.com/embed/lf4h4DwdQc8',
    },  
    156 : {
        'name' : 'Cometín',
        'type' : 'Actividad',
        'author' : 'Luis Delgadillo',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Volar es algo con lo que soñamos mucho, tan así, que inventamos los aviones, los globos aerostáticos y demás artilugios. Bueno, pues Cometín no es la excepción, este niño tiene tantas ganas de volar, que sus amigos decidieron ponerle ese sobrenombre, y que por cierto, le queda muy bien.',
        'url' : 'https://www.youtube.com/embed/v82D3FKLexo',
    },
    152 : {
        'name' : 'Hilos de palabra y canto',
        'type' : 'Narración',
        'author' : 'Lidia Zaragoza',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.  Hilos que van y vienen de boca a oído y que son el camino de encuentro entre un libro y un posible lector y de un cuento con su propio canto.',
        'url' : 'https://www.youtube.com/embed/FWtPZK9N10U',
    }, 
    34 : {
        'name' : 'El efecto mariposa',
        'type' : 'Narración',
        'author' : 'Antonio Zacruz',
        'description' : 'Recomendado para niñas y niños a partir de 8 años de edad. Esta historia acaba de nacer y sólo se podrá repetir viendo el video otra vez. Antonio Zacruz improvisa esta historia efímera que nace de una palabra encontrada en un libro. Una forma juguetona, como el aleteo de una mariposa, de inventar historias encadenadas por el hecho de que a toda acción, corresponde una reacción.',
        'url' : 'https://www.youtube.com/embed/oCA63J8L_VE',
    }, 
    137 : {
        'name' : '¡A volar tus miedos!',
        'type' : 'Actividad',
        'author' : 'Cristóbal Barreto',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Materiales: • Hojas de papel blancas o de colores • Lápices de colores. Basado en "El libro valiente" de Moni Port, editorial Takatuka. Se retoman algunos puntos de los que habla el libro y a partir de esto se realiza una actividad en la que niñas y niños escriben y/o dibujan sus miedos. Se propone después hacer un avioncito de papel con la hoja del dibujo y ¡a echar los miedos a volar!',
        'url' : 'https://www.youtube.com/embed/mzmBEcut_rc',
    }, 
    159 : {
        'name' : 'Las tres cabras Gruff',
        'type' : 'Narración oral',
        'author' : 'Ángela Camacho',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Tres cabras hermanas de gran comer ya han acabado con toda la verde pradera de la montaña, descubren que del otro lado del río hay un hermoso y verde pastizal, sólo que debajo del puente vive un terrible ogro. ¿Cómo resolverán el problema?',
        'url' : 'https://www.youtube.com/embed/l26hIDhbfV4',
    }, 
    98 : {
        'name' : 'El poema tiene pies: cómo hacer poemas en voz alta',
        'type' : 'Laboratorio creativo',
        'author' : 'Cynthia Franco',
        'description' : 'Recomendado para adolescentes a partir de 13 años de edad. Vamos a la parte divertida de la poesía: ponerle imaginación, sonido, juego y cuerpo. El poema está hecho para hacerlo respirar. Un poema con pies. Hacerlo que baile al ritmo de nuestras palabras. Al ritmo de nuestros latidos. Caminamos con el texto. Hay quienes son muy buenos para improvisar o improversar, hay quienes prefieren escribir y luego memorizarlos, yo te voy a mostrar cómo le hago en siete pasos.',
        'url' : 'https://www.youtube.com/embed/WVtAWFD-gzs',
    }, 
    115 : {
        'name' : 'El torito jarocho',
        'type' : 'Actividad',
        'author' : 'Kumaltik',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. "El torito jarocho" forma parte de su concierto “Ay, que sí, que sí, qué no” donde se recrea la historia de la tradición musical campesina del sur de Veracruz, repleta de sones jarochos que se destacan por su fina y bella poesía, además de un buen zapateado que niñas y niños pueden bailar en casa.',
        'url' : 'https://www.youtube.com/embed/Kp3skoHdvtg',
    },
    88 : {
        'name' : 'Saraí Mérida recomienda',
        'type' : 'Fomento a la lectura',
        'author' : 'Saraí Mérida',
        'description' : 'Chupa ladxidua’ / Dos es mi corazón .Para niñas y niños a partir de 8 años de edad. Chupa ladxidua’- Dos es mi corazón  de Irma Pineda Ilustrado por Niñas y niños de Juchitán de Zaragoza, Oaxaca. Editorial Alas y Raíces, 2019. Niñas y niños del municipio Juchitán de Zaragoza, en Oaxaca, se dan cita en este libro para ilustrar fragmentos de la poesía de Irma Pineda. Dos es mi corazón es un libro que recoge los versos en español y zapoteco de la poeta y los deja en manos de los pinceles de niñas y niños para darles color con su imaginación.',
        'url' : 'https://www.youtube.com/embed/-YzMuuDgm9s',
    },
    161 : {
        'name' : 'Los animales no eran así ',
        'type' : 'Narración oral',
        'author' : 'Aníbal Hoyos',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Los animales no siempre fueron como los conocemos y aquí te vamos a contar de tres muy conocidos y de cómo obtuvieron su forma actual. Estos relatos que cuenta Aníbal Hoyos son sólo una probadita de lo que cuenta la leyenda del Fuego Nuevo.',
        'url' : 'https://www.youtube.com/embed/HIJF2FUCtEE',
    },
    165 : {
        'name' : 'Bicho y hecho',
        'type' : 'Presentación artística, Música',
        'author' : 'Cántaro',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. ¿Te has preguntado con quién más vives en tu casa? Sí tienes plantas o un jardín sabes de que hablamos; nuestros amigos patudos, los más pequeños del reino animal. Unos zumban, otros silban cuando hacen vibrar sus alas, así es, son los bichos amistosos que hacen fiesta cuando duermes.',
        'url' : 'https://www.youtube.com/embed/i_H2BXHZKgA',
    },
    139 : {
        'name' : 'Teatro de sombras',
        'type' : 'Actividad',
        'author' : 'Tanya Covarrubias y Cristóbal Barreto',
        'description' : 'Basado en El libro valiente de Moni Port, editorial Takatuka. Recomendado para niñas y niños a partir de 3 años de edad. Muchas personas le tienen miedo a lo desconocido, como dice el libro titulado El libro valiente. En la oscuridad, por ejemplo, suelen proyectarse sombras que asustan a muchos. En este video descubriremos cómo hacer un teatro de sombras y jugar con ellas.',
        'url' : 'https://www.youtube.com/embed/duDow9vuepg',
    }, 
    163  : {
        'name' : 'Mi perro corrientón',
        'type' : 'Presentación artística, Música',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. El solovino, el pulgas, el chicharrón: son algunos apodos que conocemos para los perritos sin raza y sin amigo humano que los tenga en casa, pero que amamos y respetamos mucho, sobre todo cuando los hacemos parte de nuestra familia y se vuelven indispensables para nuestra felicidad. Corrientón es un perrito adoptado y muy travieso, pero de puritito corazón, conoce su historia en esta canción.',
        'url' : 'https://www.youtube.com/embed/6SesveX2PNw',
    }, 
    150 : {
        'name' : 'Una línea... muchas ideas',
        'type' : 'Laboratorio creativo',
        'author' : 'Flor Sandoval',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad, acompañados de un adulto. Un espacio, tu casa. Un objeto, una cuerda. Sólo con eso podrás inventar juegos, formas, imágenes y otras cosas más. Materiales: • Lazo • Gises o crayolas • Hoja blanca',
        'url' : 'https://www.youtube.com/embed/mdwBa2hPMM4',
    },
    11 : {
        'name' : 'Trabalenguas',
        'type' : 'Narración y oralidad',
        'author' : 'Raúl Pérez Buendía',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. El perro de San Roque y La perra y la parra de Guerra y Parra son dos trabalenguas que propone Raúl Pérez Buendía como un reto para desenredar la lengua. ¿Te animas a intentar?',
        'url' : 'https://www.youtube.com/embed/67_7AtP759o',
    },
    7 : {
        'name' : 'Tiemblen dragones',
        'type' : 'Narración oral y en LSM',
        'author' : 'Ana Cristina Ortega y Antonio Zacruz',
        'description' : 'Basada en Tiemblen dragones de Robert Munsch, Editorial Castillo. Con interpretación en Lengua Mexicana de Señas. Recomendado para niñas y niños a partir de 7 años de edad. La princesa Elizabeth tiene muchos vestidos, un hermoso castillo y un príncipe con el que se quiere casar, todo parece perfecto; hasta que un día un terrible dragón llega a cambiar todos sus planes. Esta es la historia de una princesa muy valiente, ¿te gustaría conocerla?',
        'url' : 'https://www.youtube.com/embed/BGRNCi9t7T4',
    },
    127 : {
        'name' : 'Flauta transversa de PVC',
        'type' : 'Laboratorio creativo, música',
        'author' : 'Fores Basura, integrante de Orquesta Basura',
        'description' : 'Recomendado para adolescentes a partir de 13 años, con supervisión de un adulto. Materiales: • Tubo de PVC de ½” pulgada • Taladro • Broca de 5/16 • Lápiz • Bola de unicel de ½ “pulgada • Cinta métrica o regla. Este tutorial es todo un reto, vas a construir una flauta transversal de un tubo de PVC, sí, esos que se utilizan para las tuberías de agua, por su composición es perfecto para crear un instrumento musical de viento, además de económico y accesible.',
        'url' : 'https://www.youtube.com/embed/CRfWFAN3axs',
    },     
    31 : {
        'name' : 'El señor Don Gato',
        'type' : 'Presentación artística',
        'author' : 'Lidia Zaragoza',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Hilos que van y vienen de boca a oído y que son el camino de encuentro entre un libro y un posible lector y de un cuento con su propio canto.',
        'url' : 'https://www.youtube.com/embed/3P_6HTtI0_U',
    },   
    135 : {
        'name' : 'Malabares con frutas: Desmenuzando el Delirio Culinario (Tercera parte) (Taller)',
        'type' : 'Actividad',
        'author' : 'Compañía Circonciente',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Giorgo Peperonne, el chef de fama internacional trae para nosotros recetas para hacer en casa; solo se necesitan limones o naranjas, así de fácil, bueno, cada receta va subiendo grados de dificultad, pero con mucha práctica en casa seguro lo lograrás.',
        'url' : 'https://www.youtube.com/embed/Iwra56LQTP4',
    }, 
    162 : {
        'name' : 'Sherwood (Música)',
        'type' : 'Actividad',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/6ke6NaufM_w',
    }, 
    48 : {
        'name' : 'Ángel Aranda recomienda "El árbol habla de Octavio Paz"',
        'type' : 'Fomento a la Lectura',
        'author' : 'Autor',
        'description' : 'El árbol habla de Octavio Paz. Ilustraciones: Niñas y niños del barrio de Mixcoac, Ciudad de México. Editorial: Alas y Raíces. Año de edición: 2015',
        'url' : 'https://www.youtube.com/embed/e92apwGsjS4',
    }, 
    41 : {
        'name' : 'Son de la iguana, son tradicional del estado de Veracruz',
        'type' : 'Música',
        'author' : 'Kevin Galeana',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad. Es la hora de zapatear y versar como lo hacen los jarochos. Esta cápsula te dejará moviendo la cabeza, los hombros, los pies y las manos al son de la Iguana.',
        'url' : 'https://www.youtube.com/embed/TqWn91mKb6I',
    },
    71 : {
        'name' : 'Gifmagínate',
        'type' : 'Laboratorio creativo',
        'author' : 'Itzel Ortega',
        'description' : 'Recomendado para niñas y niños a partir de 6 años, con supervisión de un adulto. Como sabes, los Gifs, te ayudan a condensar información para transmitir emociones y mensajes cuando estás chateando con alguien. En este taller Itzel Ortega nos enseña a elaborar un Gif animado a través de la técnica del stop motion. Materiales: • Hojas de papel • Lápices de colores y/o marcadores • Tijeras • Pegamento',
        'url' : 'https://www.youtube.com/embed/eJFc7_qyxHM',
    },
    76 : {
        'name' : 'Calavera',
        'type' : 'Música',
        'author' : 'David Alva',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Canción de la calavera para divertirse sustituyendo vocales, estimulando así el lenguaje y memorización de las palabras en niñas y niños a través del canto.',
        'url' : 'https://www.youtube.com/embed/_U7eYDBciTk',
    }, 
    93 : {
        'name' : 'Tres flores. Esgrafiado en negativo y positivo',
        'type' : 'Laboratorio creativo',
        'author' : 'Manuel Reyes Tissera',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad, con supervisión de un adulto. Materiales: • Hojas de papel • Lápices de colores y/o marcadores • Tijeras • Pegamento. Aprenderás pintura de paisaje breve, en esgrafiado positivo y negativo, además de aprender a hacer algunos árboles y flores imaginarias.',
        'url' : 'https://www.youtube.com/embed/AptDc1B9FME',
    }, 
    52 : {
        'name' : 'Cantos aiepo',
        'type' : 'Laboratorio creativo',
        'author' : 'Edith Álvarez Gigi',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/EbzlCGxcJ20',
    },  
    79 : {
        'name' : 'Spoken versos',
        'type' : 'Laboratorio creativo',
        'author' : 'Comikk MG',
        'description' : 'Recomendado para niñas y niños a partir de 10 años de edad. ¿Sabes qué es el retruécano, el calambur y la jitanjáfora? En este taller Comikk MG te enseña qué son estas tres figuras retóricas y hasta dónde pueden llegar tus palabras y versos usándolas.',
        'url' : 'https://www.youtube.com/embed/F4o4_RueKTI',
    }, 
    166 : {
    	'name' : 'Chihuahua: La historia de la Cabra Cabratis',
        'type' : 'Narración',
        'author' : 'Luisa Samaniego, integrante de la compañía de títeres Cachiripa',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad. Inspirada en un cuento anónimo de la lírica infantil latinoamericana, interpretado con títeres objetos de manipulación a la vista que nos recuerdan que no debes de confiar en desconocidos.',
        'url' : 'https://www.youtube.com/embed/LQCUGZsjfWo',
    }, 
    167 : {
        'name' : 'Colima: Dado en movimiento',
        'type' : 'Laboratorio creativo',
        'author' : 'Alejandra Ibáñez, Tallerista',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad. Materiales: • Cartulina • Hoja blanca • Tijeras • Lápiz o plumón • Regla • Pegamento. Actividad de motricidad mediante circuitos cortos de actividad física en relación al material didáctico elaborado (el dado) para estimular el área motriz y generar un ambiente de convivencia.',
        'url' : 'https://www.youtube.com/embed/_X5Z0W94QSY',
    },
    56 : {
        'name' : 'Jalisco: El ratón viajero',
        'type' : 'Narración',
        'author' : 'Yademira Barrragán y Dato López',
        'description' : 'Recomendado para niñas y niños a partir de 5 años de edad. Con tan bonito sol y tan bonito día, el ratón Simón quiere navegar sólo que el viento parece no soplar a su favor, así que tendrá que pedir ayuda a los cuatro vientos para poder mover su barca. ¿Será que lo pueda lograr?',
        'url' : 'https://www.youtube.com/embed/5jUenFbImsQ',
    },
    168 : {
        'name' : 'Chihuahua: Truco de magia con una tarjeta',
        'type' : 'Laboratorio creativo',
        'author' : 'Gustavo Márquez',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Materiales: • Hojas de colores • Cartón • Lápiz • Tijeras • Listón • Regla • Pegamento. Creando una tarjeta móvil con papel y cartón podremos hacer un truco de magia al desaparecer una moneda.',
        'url' : 'https://www.youtube.com/embed/DL-K6ZNZy-c',
    }, 
    166 : {
        'name' : 'Jalisco: Kikiri Koko',
        'type' : 'Música',
        'author' : 'Cristina Martínez y Sergio de Arreola, integrantes de "A la Deriva Teatro"',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/QqNRPrYM2dQ',
    }, 
    187 : {
        'name' : 'Ramón preocupón. Chihuahua',
        'type' : 'Narración y Tradición Oral',
        'author' : 'Con Simuchí Anará (Raquel Muñoz Loya e Irma Loya)',
        'description' : 'Narración basada en Ramón preocupón de Anthony Browne. Ramón es un niño que se preocupa y sufre por todo, hasta que su abuelita le regala algo que le ayudará a estar más tranquilo, ¿qué será? Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/w9LyhhVFNi4',
    },
    170 : {
        'name' : ' La cabra que no quería comer. Coahuila',
        'type' : 'Narración',
        'author' : 'Anette Fonseca Moka, Cuentacuentos',
        'description' : 'Para niñas y niños a partir de 3 años de edad. Narración basada en "La cabra que no quería comer" de Esther Hernández Palacios. Matilde era una cabra melindrosa, hasta que por fin su mamá logró que comiera con gusto, después de hacer mil intentos. Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https://www.youtube.com/embed/KlVWYP-dAes',
    }, 
    171 : {
        'name' : 'Transfer natural. Colima.',
        'type' : 'Taller',
        'author' : 'Héctor Aburto',
        'description' : 'Para niñas y niños a partir de 6 años de edad. Realización de gráfica por medio del transfer de hojas orgánicas entintadas sobre papel marquilla, con ayuda de herramientas que contamos en nuestros hogares.',
        'url' : 'https://www.youtube.com/embed/ok6antrHxB8',
    }, 
    198 : {
        'name' : 'Mi día de suerte. Jalisco',
        'type' : 'Narración',
        'author' : 'María Tránsito Campechano',
        'description' : 'Recomendado para niñas y niños a partir de 6 años de edad. Narración basada en "Mi día de suerte" de Keiko Kasza. Un cerdito busca la manera de sobrevivir sin mucho esfuerzo, visitando cada día a un animal distinto, con la dosis de emoción que da visitar a sus depredadores naturales.',
        'url' : 'https://www.youtube.com/embed/6ALAfyMDqmE',
    }, 
    169 : {
        'name' : 'Kuira ba. Leyendas rarámuris: El coyote y el conejo. Chihuahua. ',
        'type' : ' Narración musicalizada',
        'author' : 'Eliud Mortor',
        'description' : 'Para niñas y niños a partir de 6 años de edad. Se narra el significado de algunas palabras y tradiciones de los rarámuri, como la palabra Korima (que significa "compartir"), la importancia de la vestimenta tradicional y la danza tradicional. Después se cuenta la leyenda del Coyote y el Conejo, historia que narra el por qué los coyotes aúllan mirando a la luna y por qué se ve un conejo en ella. Recomendado para niñas y niños a partir de 6 años de edad.',
        'url' : 'https://www.youtube.com/embed/KgI9YCaRGvg',
    },
    164 : {
        'name' : 'El más chido chiflador',
        'type' : 'Música',
        'author' : 'Pedro Sandoval, integrante de Los Botes Cantan',
        'description' : 'Para niñas y niños a partir de 6 años de edad. Canción para motivarte a chiflar. ¡Chiflar! ¡Ufff! ¡Qué habilidad tan peculiar! Es soplar con estilo, pura determinación necesitas ser el más chido chiflador, ¡Ah pero como cuesta dominar este arte ancestral! Subir el paladar, hacer la boca como una cueva y soplar, pero no tan fuerte porque no suena. Y una vez que lo has logrado, puedes echarte las canciones que más te gustan en chiflidos.',
        'url' : 'https://www.youtube.com/embed/7RoGRqtKbVE',
    }, 
    189 : {
        'name' : 'Arte para los primeros años: Música e improvisación. Jalisco',
        'type' : 'Actividades para la primera infancia',
        'author' : 'Susana Romo y Cristina Martínez, integrantes de A la Deriva Teatro',
        'description' : 'La música y el juego son parte fundamental en las trayectorias de desarrollo de niños y niñas en sus primeros años. A la Deriva Teatro te sugiere algunas actividades, como inventar canciones o historias con lo que está a tu  alrededor dentro de casa y generar así un espacio lúdico que provoque tranquilidad, sonrisas y conexión con tu bebé. Para padres, tutores, maestros y cuidadores.',
        'url' : 'https://www.youtube.com/embed/b47vOgKH7lk',
    }, 
  
    193 : { 
        'name' : 'Buscar a los pollitos. Jalisco',
        'type' : 'Música',
        'author' : 'Cristina Martínez y Sergio Arreola, integrantes de A la Deriva Teatro',
        'description' : 'Para niñas y niños a partir de 3 años de edad. Para los bebés, la música constituye un elemento clave a la hora de descubrir y hacer contacto con el mundo que les rodea. "A la Deriva Teatro" te invita a jugar con la canción “Buscando a los pollitos” y generar un momento especial con tu bebé, tejiendo un ambiente de amor, confianza, protección y tranquilidad a través de la música.',
        'url' : 'https://www.youtube.com/embed/ToV4WS7EIZo',
    },  
    173 : {
        'name' : 'Sonoridades. Composición con frascos. Chihuahua.',
        'type' : 'Taller',
        'author' : 'Eliud Mortor',
        'description' : 'Para niñas y niños a partir de 6 años de edad.  Se experimenta con distintas técnicas para crear música y construir objetos sonoros donde los niños, niñas y adolescentes puedan despertar su creatividad y realizar una composición musical (sonora) y de esta manera acercarlos a la música de una forma relajada y sobre todo divertida.',
        'url' : 'https://www.youtube.com/embed/Mk_slhcMg6I',
    }, /*
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
    # : {
        'name' : 'Título',
        'type' : 'Actividad',
        'author' : 'Autor',
        'description' : 'Recomendado para niñas y niños a partir de 3 años de edad.',
        'url' : 'https:LINK',
    },
     */
};
